// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webAPI.Data;

namespace webAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211207034946_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("webAPI.Models.Biblioteca", b =>
                {
                    b.Property<int>("BibliotecaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CategoriaLibro")
                        .HasColumnType("text");

                    b.Property<string>("FechaDeLanzamiento")
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .HasColumnType("text");

                    b.Property<string>("Libro")
                        .HasColumnType("text");

                    b.Property<string>("NombreAutor")
                        .HasColumnType("text");

                    b.HasKey("BibliotecaID");

                    b.ToTable("Bibliotecas");
                });

            modelBuilder.Entity("webAPI.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("BibliotecaID")
                        .HasColumnType("integer");

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<string>("fullname")
                        .HasColumnType("text");

                    b.Property<decimal>("salario")
                        .HasColumnType("numeric");

                    b.HasKey("EmpleadoID");

                    b.HasIndex("BibliotecaID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("webAPI.Models.Empleado", b =>
                {
                    b.HasOne("webAPI.Models.Biblioteca", "BiliotecaID")
                        .WithMany()
                        .HasForeignKey("BibliotecaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BiliotecaID");
                });
#pragma warning restore 612, 618
        }
    }
}
